using System;
using UnityEngine;

// Data contract for the painted 1851 campaign map.
// Generated by tools/map1851/build_map.py into Resources/Map1851/Denmark1851_Map.json.

[Serializable]
public sealed class Map1851Extent
{
    public float lonMin;
    public float lonMax;
    public float latMin;
    public float latMax;

    public Vector2 ToUv(float lat, float lon)
    {
        return new Vector2((lon - lonMin) / (lonMax - lonMin), (lat - latMin) / (latMax - latMin));
    }
}

[Serializable]
public sealed class Map1851Size
{
    public float width;
    public float height;
}

[Serializable]
public sealed class Map1851City
{
    public string name;
    public float lat;
    public float lon;
    public int pop;
    public string region;
    public bool capital;
    public bool bornholm;
}

[Serializable]
public sealed class Map1851Label
{
    public string text;
    public float lat;
    public float lon;
    public string kind;
}

[Serializable]
public sealed class Map1851Data
{
    public string version;
    public Map1851Extent extent;
    public Map1851Size sizeKm;
    public float detailTileKm;
    public Map1851Extent bornholm;
    public Map1851City[] cities;
    public Map1851City[] foreignCities;
    public Map1851Label[] labels;

    public static string RegionName(string code)
    {
        switch (code)
        {
            case "K": return "Kongeriget Danmark";
            case "S": return "Hertugdømmet Slesvig";
            case "H": return "Hertugdømmerne Holsten og Lauenborg";
            default: return "Udland";
        }
    }
}
