using System;
using UnityEngine;

// Data contract for the painted 1851 campaign map.
// Generated by tools/map1851/build_map.py into Resources/Map1851/Denmark1851_Map.json.

/// <summary>Geographic box of the region (informational since v00.00.15).</summary>
[Serializable]
public sealed class Map1851Extent
{
    public float lonMin;
    public float lonMax;
    public float latMin;
    public float latMax;
}

/// <summary>
/// Lambert Azimuthal Equal-Area on a sphere (as EPSG:3035, centre 52N 10E); must match
/// tools/map1851/build_map.py, which paints the map in the same projection.
/// </summary>
[Serializable]
public sealed class Map1851Projection
{
    public string type = "laea";
    public double lat0 = 52.0;
    public double lon0 = 10.0;
    public double radiusKm = 6371.0088;

    /// <summary>Degrees -> projected km (x east, y north).</summary>
    public Vector2 Forward(double lat, double lon)
    {
        double lam = (lon - lon0) * Math.PI / 180.0, phi = lat * Math.PI / 180.0, phi0 = lat0 * Math.PI / 180.0;
        double k = Math.Sqrt(2.0 / (1.0 + Math.Sin(phi0) * Math.Sin(phi) + Math.Cos(phi0) * Math.Cos(phi) * Math.Cos(lam)));
        return new Vector2((float)(radiusKm * k * Math.Cos(phi) * Math.Sin(lam)),
                           (float)(radiusKm * k * (Math.Cos(phi0) * Math.Sin(phi) - Math.Sin(phi0) * Math.Cos(phi) * Math.Cos(lam))));
    }
}

/// <summary>A projected rectangle (km) covered by a map texture.</summary>
[Serializable]
public sealed class Map1851ExtentKm
{
    public double xMin;
    public double xMax;
    public double yMin;
    public double yMax;

    /// <summary>0..1 across the rectangle; u east, v north.</summary>
    public Vector2 ToUv(Map1851Projection projection, float lat, float lon)
    {
        Vector2 p = projection.Forward(lat, lon);
        return new Vector2((float)((p.x - xMin) / (xMax - xMin)), (float)((p.y - yMin) / (yMax - yMin)));
    }
}

[Serializable]
public sealed class Map1851Size
{
    public float width;
    public float height;
}

[Serializable]
public sealed class Map1851City
{
    public string name;
    public float lat;
    public float lon;
    public int pop;
    public string region;
    public bool capital;
    public bool bornholm;
}

[Serializable]
public sealed class Map1851Label
{
    public string text;
    public float lat;
    public float lon;
    public string kind;
}

[Serializable]
public sealed class Map1851Data
{
    public string version;
    public string region;
    public Map1851Projection projection;
    public Map1851ExtentKm extentKm;
    public Map1851ExtentKm bornholmKm;
    public Map1851Extent extent;
    public Map1851Size sizeKm;
    public float detailTileKm;
    public Map1851Extent bornholm;
    public Map1851City[] cities;
    public Map1851City[] foreignCities;
    public Map1851Label[] labels;

    public static string RegionName(string code)
    {
        switch (code)
        {
            case "K": return "Kongeriget Danmark";
            case "S": return "Hertugdømmet Slesvig";
            case "H": return "Hertugdømmerne Holsten og Lauenborg";
            default: return "Udland";
        }
    }
}
